### ISSUE TITLE
Add functionality to handle forward and reverse reads

### ISSUE THREAD

**Issue by juliambrosman** [BigelowLab/gorg-classifier#10]
A suggested future improvement. I don't think there's a way to input paired reads, but please correct me if I'm wrong.

Kaiju can handle paired reads with -i and -j flags, classifier currently just uses -i for one set of input reads.

**Comment by brwnj** [comment]
i implemented this in 23b3f7092d49b066f1a1d7ecf679bb677f3a6de2 and added how to denote single- vs paired-end reads in the readme (https://github.com/BigelowLab/gorg-classifier#paired-end-data).
